services:
  app:
    build:
      context: .
      dockerfile: single-container/Dockerfile
    container_name: processos-app
    restart: unless-stopped
    ports:
      - "80:80"       # Angular via nginx
      - "8080:8080"   # API .NET direta (opcional, útil para debug)
      - "5432:5432"   # Postgres (opcional, útil para conectar DBeaver/pgAdmin)
    environment:
      APP_DB_NAME: processos_api
      APP_DB_USER: processos_api_user
      APP_DB_PASSWORD: processos_api_password
      ConnectionStrings__ProcessoConnection: "Host=localhost;Port=5432;Database=processos_api;Username=processos_api_user;Password=processos_api_password"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
